// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models;

public partial class HealthCheck
{
    public Guid HealthCheckId { get; set; }

    public Guid DonorId { get; set; }

    public double? Weight { get; set; }

    public double? Height { get; set; }

    public int? HeartRate { get; set; }

    public double? Temperature { get; set; }

    public string BloodPressure { get; set; }

    public string MedicalHistory { get; set; }

    public string CurrentMedications { get; set; }

    public string Allergies { get; set; }

    public DateOnly HealthCheckDate { get; set; }

    public string HealthCheckStatus { get; set; }

    public virtual Donor Donor { get; set; }
}